BOOKING_STATUS_HOLD = "HOLD"
BOOKING_STATUS_TRAVELER_DETAILS_PENDING = "TRAVELER_DETAILS_PENDING"
BOOKING_STATUS_AWAITING_FINAL_PAYMENT = "AWAITING_FINAL_PAYMENT"
BOOKING_STATUS_READY_FOR_OPERATOR = "READY_FOR_OPERATOR"
BOOKING_STATUS_IN_FULFILLMENT = "IN_FULFILLMENT"
BOOKING_STATUS_READY_FOR_TRAVEL = "READY_FOR_TRAVEL"
BOOKING_STATUS_COMPLETED = "COMPLETED"
BOOKING_STATUS_CANCELLED = "CANCELLED"
BOOKING_STATUS_EXPIRED = "EXPIRED"

BOOKING_STATUS_CHOICES = [
    (BOOKING_STATUS_HOLD, BOOKING_STATUS_HOLD.lower()),
    (BOOKING_STATUS_TRAVELER_DETAILS_PENDING, BOOKING_STATUS_TRAVELER_DETAILS_PENDING.lower()),
    (BOOKING_STATUS_AWAITING_FINAL_PAYMENT, BOOKING_STATUS_AWAITING_FINAL_PAYMENT.lower()),
    (BOOKING_STATUS_READY_FOR_OPERATOR, BOOKING_STATUS_READY_FOR_OPERATOR.lower()),
    (BOOKING_STATUS_IN_FULFILLMENT, BOOKING_STATUS_IN_FULFILLMENT.lower()),
    (BOOKING_STATUS_READY_FOR_TRAVEL, BOOKING_STATUS_READY_FOR_TRAVEL.lower()),
    (BOOKING_STATUS_COMPLETED, BOOKING_STATUS_COMPLETED.lower()),
    (BOOKING_STATUS_CANCELLED, BOOKING_STATUS_CANCELLED.lower()),
    (BOOKING_STATUS_EXPIRED, BOOKING_STATUS_EXPIRED.lower()),
]

BOOKING_STATUS_SET = {choice[0] for choice in BOOKING_STATUS_CHOICES}
BOOKING_STATUS_CAPACITY_SET = {
    BOOKING_STATUS_HOLD,
    BOOKING_STATUS_TRAVELER_DETAILS_PENDING,
    BOOKING_STATUS_AWAITING_FINAL_PAYMENT,
    BOOKING_STATUS_READY_FOR_OPERATOR,
    BOOKING_STATUS_IN_FULFILLMENT,
    BOOKING_STATUS_READY_FOR_TRAVEL,
}
BOOKING_STATUS_TERMINAL_SET = {
    BOOKING_STATUS_COMPLETED,
    BOOKING_STATUS_CANCELLED,
    BOOKING_STATUS_EXPIRED,
}
BOOKING_STATUS_OPERATOR_VISIBLE_SET = {
    BOOKING_STATUS_TRAVELER_DETAILS_PENDING,
    BOOKING_STATUS_AWAITING_FINAL_PAYMENT,
    BOOKING_STATUS_READY_FOR_OPERATOR,
    BOOKING_STATUS_IN_FULFILLMENT,
    BOOKING_STATUS_READY_FOR_TRAVEL,
    BOOKING_STATUS_COMPLETED,
}

PAYMENT_STATUS_UNDER_REVIEW = "UNDER_REVIEW"
PAYMENT_STATUS_APPROVED = "APPROVED"
PAYMENT_STATUS_REJECTED = "REJECTED"
PAYMENT_STATUS_NOT_SUBMITTED = "NOT_SUBMITTED"
PAYMENT_STATUS_CHOICES = [
    (PAYMENT_STATUS_UNDER_REVIEW, PAYMENT_STATUS_UNDER_REVIEW.lower()),
    (PAYMENT_STATUS_APPROVED, PAYMENT_STATUS_APPROVED.lower()),
    (PAYMENT_STATUS_REJECTED, PAYMENT_STATUS_REJECTED.lower()),
]

ISSUE_STATUS_NONE = "NONE"
ISSUE_STATUS_OPERATOR_OBJECTION = "OPERATOR_OBJECTION"
ISSUE_STATUS_REPORTED = "REPORTED"
ISSUE_STATUS_CHOICES = [
    (ISSUE_STATUS_NONE, ISSUE_STATUS_NONE.lower()),
    (ISSUE_STATUS_OPERATOR_OBJECTION, ISSUE_STATUS_OPERATOR_OBJECTION.lower()),
    (ISSUE_STATUS_REPORTED, ISSUE_STATUS_REPORTED.lower()),
]

WORKFLOW_BUCKET_VIEW_ONLY = "VIEW_ONLY"
WORKFLOW_BUCKET_READY = "READY"
WORKFLOW_BUCKET_FULFILLMENT = "FULFILLMENT"
WORKFLOW_BUCKET_READY_FOR_TRAVEL = "READY_FOR_TRAVEL"
WORKFLOW_BUCKET_ISSUES = "ISSUES"
WORKFLOW_BUCKET_COMPLETED = "COMPLETED"
WORKFLOW_BUCKET_HISTORY = "HISTORY"

WORKFLOW_BUCKET_CHOICES = {
    WORKFLOW_BUCKET_VIEW_ONLY,
    WORKFLOW_BUCKET_READY,
    WORKFLOW_BUCKET_FULFILLMENT,
    WORKFLOW_BUCKET_READY_FOR_TRAVEL,
    WORKFLOW_BUCKET_ISSUES,
    WORKFLOW_BUCKET_COMPLETED,
    WORKFLOW_BUCKET_HISTORY,
}
