# Generated by Django 5.0.6 on 2026-02-25 15:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribeUser',
            fields=[
                ('sub_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserOTP',
            fields=[
                ('otp_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=15)),
                ('otp_password', models.CharField(max_length=10, null=True)),
                ('created_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_token', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=5)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50)),
                ('user_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non-binary'), ('prefer_not_to_say', 'Prefer not to say'), ('other', 'Other')], max_length=20, null=True)),
                ('user_type', models.CharField(choices=[('user', 'User'), ('customer', 'Customer'), ('admin', 'Admin'), ('sales_director', 'Sales_Director')], max_length=50)),
                ('firebase_token', models.CharField(default='', max_length=500, null=True)),
                ('web_firebase_token', models.CharField(default='', max_length=500, null=True)),
                ('is_phone_verified', models.BooleanField(default=False, null=True)),
                ('is_email_verified', models.BooleanField(default=False, null=True)),
                ('is_address_exist', models.BooleanField(default=False, null=True)),
                ('email_otp', models.CharField(max_length=10, null=True)),
                ('otp_time', models.DateTimeField(auto_now=True)),
                ('is_notification_allowed', models.BooleanField(default=True, null=True)),
                ('user_photo', models.ImageField(blank=True, null=True, upload_to='user_images')),
                ('account_status', models.CharField(max_length=10, null=True)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('online', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserBankAccount',
            fields=[
                ('account_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_title', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=100)),
                ('branch_code', models.CharField(max_length=100)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('bank_account_for_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account_for_user', to='common.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ManageNotification',
            fields=[
                ('notification_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('notification_title', models.CharField(max_length=200)),
                ('notification_message', models.TextField(max_length=500, null=True)),
                ('is_seen', models.BooleanField(default=False)),
                ('firebase_token', models.CharField(max_length=500, null=True)),
                ('web_firebase_token', models.CharField(max_length=500, null=True)),
                ('notification_for_booking', models.CharField(default='', max_length=200, null=True)),
                ('notification_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notification_for_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_session', to='common.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='MailingDetail',
            fields=[
                ('address_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('street_address', models.CharField(max_length=300)),
                ('address_line2', models.CharField(blank=True, max_length=300, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('lat', models.CharField(blank=True, max_length=50, null=True)),
                ('long', models.CharField(blank=True, max_length=50, null=True)),
                ('mailing_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailing_session', to='common.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UserWithdraw',
            fields=[
                ('withdraw_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('withdraw_amount', models.FloatField()),
                ('request_time', models.DateTimeField(auto_now=True)),
                ('withdraw_status', models.CharField(max_length=20, null=True)),
                ('process_time', models.DateTimeField(null=True)),
                ('withdraw_backup_detail', models.TextField(null=True)),
                ('withdraw_bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdraw_bank', to='common.userbankaccount')),
                ('withdraw_for_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdraw_for_user', to='common.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('wallet_id', models.AutoField(primary_key=True, serialize=False)),
                ('wallet_code', models.CharField(max_length=100, unique=True)),
                ('wallet_amount', models.FloatField(default=0.0)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('wallet_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_session', to='common.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UserTransactionHistory',
            fields=[
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_code', models.CharField(max_length=100)),
                ('transaction_amount', models.FloatField(default=0.0)),
                ('transaction_type', models.CharField(max_length=50)),
                ('transaction_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('transaction_description', models.CharField(blank=True, max_length=200, null=True)),
                ('transaction_for_package', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_for_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_user_token', to='common.userprofile')),
                ('transaction_wallet_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_wallet_token', to='common.wallet')),
            ],
        ),
    ]
