# Generated by Django 5.0.6 on 2026-03-12 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_add_hotspot_indexes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscribeUser',
        ),
    ]
