# Generated by Django 5.0.6 on 2026-03-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_delete_subscribeuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
