# Generated by Django 5.0.6 on 2026-02-26 02:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('partners', '0003_add_package_date_range_and_optional_nights'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender', models.CharField(choices=[('User', 'user'), ('Operator', 'operator'), ('Admin', 'admin')], max_length=50)),
                ('message', models.CharField(max_length=1000)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(null=True)),
                ('is_delivered', models.BooleanField(default=False)),
                ('delivered_at', models.DateTimeField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner', to='partners.partnerprofile')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='common.userprofile')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'partner', '-date'], name='chat_chatme_user_id_43e7dc_idx'), models.Index(fields=['is_delivered'], name='chat_chatme_is_deli_13d420_idx'), models.Index(fields=['is_read'], name='chat_chatme_is_read_24fa80_idx')],
            },
        ),
    ]
