# Generated by Django 5.0.6 on 2026-03-11 16:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_merge_0003_booking_workflow_rewrite_0004_payment_transaction_number_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status_changed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('UNDER_REVIEW', 'under_review'), ('APPROVED', 'approved'), ('REJECTED', 'rejected')], max_length=50, null=True),
        ),
    ]
