# Generated by Django 5.0.6 on 2026-03-13 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_delete_custompackages'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingairlinedetail',
            name='flight_direction',
            field=models.CharField(choices=[('outbound', 'Outbound'), ('return', 'Return')], default='outbound', max_length=20),
        ),
    ]
