# Generated by Django 5.0.6 on 2026-03-15 01:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models
from pathlib import Path


def _normalize_city_key(value):
    normalized = str(value or "").strip().lower()
    if normalized == "mecca":
        return "makkah"
    return normalized


def _derive_traveler_type(booking, traveler_sequence):
    adults = int(getattr(booking, "adults", 0) or 0)
    children = int(getattr(booking, "child", 0) or 0)
    if traveler_sequence <= adults:
        return "Adult"
    if traveler_sequence <= adults + children:
        return "Child"
    return "Infant"


def _iter_city_contact_payloads(record):
    yield ("jeddah", getattr(record, "jeddah_name", None), getattr(record, "jeddah_number", None))
    yield ("makkah", getattr(record, "mecca_name", None), getattr(record, "mecca_number", None))
    yield ("madinah", getattr(record, "madinah_name", None), getattr(record, "madinah_number", None))
    yield ("taif", getattr(record, "taif_name", None), getattr(record, "taif_number", None))
    yield ("riyadh", getattr(record, "riyadh_name", None), getattr(record, "riyadh_number", None))


def backfill_booking_contracts(apps, schema_editor):
    Booking = apps.get_model("booking", "Booking")
    BookingDocuments = apps.get_model("booking", "BookingDocuments")
    BookingGroup = apps.get_model("booking", "BookingGroup")
    BookingHotelAndTransport = apps.get_model("booking", "BookingHotelAndTransport")
    BookingHotelFulfillment = apps.get_model("booking", "BookingHotelFulfillment")
    BookingTransportFulfillment = apps.get_model("booking", "BookingTransportFulfillment")
    PassportValidity = apps.get_model("booking", "PassportValidity")
    TravelerIssue = apps.get_model("booking", "TravelerIssue")

    for booking in Booking.objects.all().iterator():
        booking_groups = list(BookingGroup.objects.filter(booking=booking).order_by("sequence", "label", "group_id"))
        if booking_groups:
            default_group = booking_groups[0]
        else:
            default_group = BookingGroup.objects.create(
                booking=booking,
                label="Group 1",
                sequence=1,
            )

        passport_queryset = PassportValidity.objects.filter(
            passport_for_booking_number=booking
        ).order_by("passport_id")
        existing_passports = list(passport_queryset)
        if existing_passports:
            for traveler_sequence, passport in enumerate(existing_passports, start=1):
                update_fields = []
                if not getattr(passport, "booking_group_id", None):
                    passport.booking_group = default_group
                    update_fields.append("booking_group")
                if int(getattr(passport, "traveler_sequence", 0) or 0) != traveler_sequence:
                    passport.traveler_sequence = traveler_sequence
                    update_fields.append("traveler_sequence")
                if not getattr(passport, "traveler_type", None):
                    passport.traveler_type = _derive_traveler_type(booking, traveler_sequence)
                    update_fields.append("traveler_type")
                if update_fields:
                    passport.save(update_fields=update_fields)
        else:
            traveler_total = max(
                int(getattr(booking, "adults", 0) or 0)
                + int(getattr(booking, "child", 0) or 0)
                + int(getattr(booking, "infants", 0) or 0),
                0,
            )
            for traveler_sequence in range(1, traveler_total + 1):
                PassportValidity.objects.create(
                    passport_for_booking_number=booking,
                    booking_group=default_group,
                    traveler_sequence=traveler_sequence,
                    traveler_type=_derive_traveler_type(booking, traveler_sequence),
                )
            existing_passports = list(
                PassportValidity.objects.filter(passport_for_booking_number=booking).order_by("passport_id")
            )

        for passport in existing_passports:
            if getattr(passport, "report_rabbit", False):
                TravelerIssue.objects.get_or_create(
                    booking=booking,
                    traveler=passport,
                    issue_type="REPORTED",
                    status="open",
                )

    for document in BookingDocuments.objects.all().iterator():
        update_fields = []
        if not getattr(document, "document_category", None) and getattr(document, "document_for", None):
            document.document_category = document.document_for
            update_fields.append("document_category")
        if not getattr(document, "document_scope", None):
            document.document_scope = "booking"
            update_fields.append("document_scope")
        if not getattr(document, "document_title", None):
            document_link = getattr(document, "document_link", None)
            document_name = Path(str(document_link.name or "")).name if document_link else ""
            document.document_title = document_name or getattr(document, "document_for", "")
            update_fields.append("document_title")
        if update_fields:
            document.save(update_fields=update_fields)

    for legacy_record in BookingHotelAndTransport.objects.select_related("hotel_or_transport_for_booking").all().iterator():
        booking = getattr(legacy_record, "hotel_or_transport_for_booking", None)
        if booking is None:
            continue

        detail_for = str(getattr(legacy_record, "detail_for", "") or "").strip().lower()
        if detail_for == "hotel":
            for city_key, contact_name, contact_phone in _iter_city_contact_payloads(legacy_record):
                if not any([contact_name, contact_phone]):
                    continue
                BookingHotelFulfillment.objects.get_or_create(
                    hotel_for_booking=booking,
                    city=_normalize_city_key(city_key),
                    defaults={
                        "hotel_name": None,
                        "contact_name": contact_name,
                        "contact_phone": contact_phone,
                        "note": getattr(legacy_record, "comment_1", None),
                    },
                )
        elif detail_for == "transport":
            if BookingTransportFulfillment.objects.filter(transport_for_booking=booking).exists():
                continue

            primary_contact_name = None
            primary_contact_phone = None
            for _city_key, contact_name, contact_phone in _iter_city_contact_payloads(legacy_record):
                if contact_name or contact_phone:
                    primary_contact_name = contact_name
                    primary_contact_phone = contact_phone
                    break

            has_details = any(
                [
                    primary_contact_name,
                    primary_contact_phone,
                    getattr(legacy_record, "comment_1", None),
                    getattr(legacy_record, "comment_2", None),
                ]
            )
            BookingTransportFulfillment.objects.create(
                transport_for_booking=booking,
                transport_mode="details_only" if has_details else "none",
                contact_name=primary_contact_name,
                contact_phone=primary_contact_phone,
                route_summary=getattr(legacy_record, "comment_2", None),
                note=getattr(legacy_record, "comment_1", None),
            )


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_bookinghotelandtransport_extra_city_contacts'),
        ('partners', '0005_remove_ziyarah_package_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='is_check_in_madinah',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='is_check_in_makkah',
        ),
        migrations.AddField(
            model_name='bookingdocuments',
            name='document_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bookingdocuments',
            name='document_scope',
            field=models.CharField(choices=[('booking', 'booking'), ('group', 'group'), ('traveler', 'traveler')], default='booking', max_length=20),
        ),
        migrations.AddField(
            model_name='bookingdocuments',
            name='document_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='bookingdocuments',
            name='traveler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='booking.passportvalidity'),
        ),
        migrations.AddField(
            model_name='passportvalidity',
            name='room_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='passportvalidity',
            name='traveler_sequence',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='passportvalidity',
            name='traveler_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bookingdocuments',
            name='document_link',
            field=models.FileField(blank=True, null=True, upload_to='user_images'),
        ),
        migrations.AlterField(
            model_name='bookingobjections',
            name='required_document_for_objection',
            field=models.FileField(blank=True, null=True, upload_to='user_images'),
        ),
        migrations.AlterField(
            model_name='passportvalidity',
            name='user_passport',
            field=models.FileField(blank=True, null=True, upload_to='passport_uploads'),
        ),
        migrations.AlterField(
            model_name='passportvalidity',
            name='user_photo',
            field=models.FileField(blank=True, null=True, upload_to='passport_uploads'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_photo',
            field=models.FileField(blank=True, null=True, upload_to='payment_uploads'),
        ),
        migrations.AlterField(
            model_name='userrequireddocuments',
            name='user_document',
            field=models.FileField(blank=True, null=True, upload_to='user_images'),
        ),
        migrations.CreateModel(
            name='BookingGroup',
            fields=[
                ('group_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_groups', to='booking.booking')),
            ],
            options={
                'ordering': ['sequence', 'label'],
            },
        ),
        migrations.AddField(
            model_name='bookingdocuments',
            name='booking_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='booking.bookinggroup'),
        ),
        migrations.AddField(
            model_name='passportvalidity',
            name='booking_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travelers', to='booking.bookinggroup'),
        ),
        migrations.CreateModel(
            name='BookingHotelFulfillment',
            fields=[
                ('fulfillment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=100)),
                ('hotel_name', models.CharField(blank=True, max_length=150, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('shared_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('hotel_for_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_fulfillments', to='booking.booking')),
                ('package_hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_fulfillments', to='partners.huzhoteldetail')),
            ],
        ),
        migrations.CreateModel(
            name='BookingTransportFulfillment',
            fields=[
                ('transport_fulfillment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transport_mode', models.CharField(choices=[('none', 'none'), ('ticket_only', 'ticket_only'), ('details_only', 'details_only'), ('details_and_ticket', 'details_and_ticket')], default='none', max_length=32)),
                ('transport_name', models.CharField(blank=True, max_length=100, null=True)),
                ('transport_type', models.CharField(blank=True, max_length=100, null=True)),
                ('route_summary', models.CharField(blank=True, max_length=250, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('ticket_reference', models.CharField(blank=True, max_length=120, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('shared_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('transport_for_booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transport_fulfillment', to='booking.booking')),
            ],
        ),
        migrations.CreateModel(
            name='TravelerIssue',
            fields=[
                ('traveler_issue_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issue_type', models.CharField(choices=[('REPORTED', 'reported'), ('RABBIT', 'rabbit')], default='REPORTED', max_length=20)),
                ('status', models.CharField(choices=[('open', 'open'), ('resolved', 'resolved')], default='open', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traveler_issues', to='booking.booking')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_traveler_issues', to='partners.partnerprofile')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_traveler_issues', to='partners.partnerprofile')),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traveler_issues', to='booking.passportvalidity')),
            ],
        ),
        migrations.AddIndex(
            model_name='bookinggroup',
            index=models.Index(fields=['booking', 'sequence'], name='booking_group_sequence_idx'),
        ),
        migrations.AddIndex(
            model_name='bookinghotelfulfillment',
            index=models.Index(fields=['hotel_for_booking', 'city'], name='booking_hotel_city_idx'),
        ),
        migrations.AddIndex(
            model_name='travelerissue',
            index=models.Index(fields=['booking', 'status'], name='trav_issue_book_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='travelerissue',
            index=models.Index(fields=['traveler', 'status'], name='trav_issue_trav_stat_idx'),
        ),
        migrations.RunPython(backfill_booking_contracts, noop_reverse),
    ]
