# Generated by Django 5.0.6 on 2026-03-15 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_remove_booking_is_check_in_madinah_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passportvalidity',
            name='report_rabbit',
        ),
        migrations.DeleteModel(
            name='BookingHotelAndTransport',
        ),
    ]
