from django.urls import path

from booking import manage_partner_booking

from . import (
    forgot_password,
    package_management,
    partner_accounts_and_transactions,
    partner_profile,
)
from .views import operator_packages


urlpatterns = [
    path("packages/public/", package_management.GetHuzShortPackageForWebsiteView.as_view(), name="v1-public-packages-list"),
    path("packages/public/featured/", package_management.GetHuzFeaturedPackageForWebsiteView.as_view(), name="v1-public-packages-featured"),
    path("packages/public/detail/", package_management.GetHuzPackageDetailForWebsiteView.as_view(), name="v1-public-packages-detail"),
    path("packages/public/search/", package_management.GetSearchPackageByCityNDateView.as_view(), name="v1-public-packages-search"),

    path("operator/auth/login/", partner_profile.PartnerLoginView.as_view(), name="v1-operator-auth-login"),
    path("operator/auth/users/exists/", partner_profile.IsPartnerExistView.as_view(), name="v1-operator-auth-user-exists"),
    path("operator/auth/accounts/", partner_profile.CreatePartnerProfileView.as_view(), name="v1-operator-auth-accounts"),
    path("operator/auth/otp/resend/", partner_profile.SendEmailOTPView.as_view(), name="v1-operator-auth-otp-resend"),
    path("operator/auth/otp/verify/", partner_profile.MatchEmailOTPView.as_view(), name="v1-operator-auth-otp-verify"),
    path("operator/auth/password/forgot/", forgot_password.ForgotEmail.as_view(), name="v1-operator-auth-password-forgot"),
    path("operator/auth/password/reset/", forgot_password.UpdatePassword.as_view(), name="v1-operator-auth-password-reset"),

    path("operator/me/usernames/exists/", partner_profile.CheckPartnerUsernameAvailabilityView.as_view(), name="v1-operator-username-exists"),
    path("operator/me/profile/", partner_profile.GetPartnerProfileView.as_view(), name="v1-operator-profile"),
    path("operator/me/address/", partner_profile.GetPartnerAddressView.as_view(), name="v1-operator-address"),
    path("operator/me/address/upsert/", partner_profile.UpdatePartnerAddressView.as_view(), name="v1-operator-address-upsert"),
    path("operator/me/services/", partner_profile.PartnerServicesView.as_view(), name="v1-operator-services"),
    path("operator/me/profile/password/", partner_profile.ChangePasswordView.as_view(), name="v1-operator-password"),
    path("operator/me/profile/avatar/", partner_profile.UpdatePartnerAvatarView.as_view(), name="v1-operator-avatar"),
    path("operator/me/company/profile/", partner_profile.UpdateBusinessProfileView.as_view(), name="v1-operator-company-profile"),
    path("operator/me/company/logo/", partner_profile.UpdateCompanyLogoView.as_view(), name="v1-operator-company-logo"),
    path("operator/me/individual/profile/", partner_profile.UpdatePartnerIndividualProfileView.as_view(), name="v1-operator-individual-profile"),
    path("operator/me/wallet/banks/", partner_accounts_and_transactions.ManagePartnerBankAccountView.as_view(), name="v1-operator-wallet-banks"),
    path("operator/me/wallet/withdrawals/", partner_accounts_and_transactions.ManagePartnerWithdrawView.as_view(), name="v1-operator-wallet-withdrawals"),
    path("operator/me/wallet/transactions/", partner_accounts_and_transactions.GetPartnerAllTransactionHistoryView.as_view(), name="v1-operator-wallet-transactions"),
    path("operator/me/wallet/summary/", partner_accounts_and_transactions.GetPartnerTransactionOverallSummaryView.as_view(), name="v1-operator-wallet-summary"),
    path("operator/me/packages/", operator_packages.GetHuzShortPackageByTokenView.as_view(), name="v1-operator-packages"),
    path("operator/me/packages/detail/", operator_packages.GetHuzPackageDetailByTokenView.as_view(), name="v1-operator-package-detail"),
    path("operator/me/packages/statistics/", operator_packages.GetPartnersOverallPackagesStatisticsView.as_view(), name="v1-operator-package-statistics"),
    path("operator/me/packages/basic/", operator_packages.CreateHuzPackageView.as_view(), name="v1-operator-package-basic"),
    path("operator/me/packages/airline/", operator_packages.CreateHuzAirlineView.as_view(), name="v1-operator-package-airline"),
    path("operator/me/packages/transport/", operator_packages.CreateHuzTransportView.as_view(), name="v1-operator-package-transport"),
    path("operator/me/packages/hotel/", operator_packages.CreateHuzHotelView.as_view(), name="v1-operator-package-hotel"),
    path("operator/me/packages/ziyarah/", operator_packages.CreateHuzZiyarahView.as_view(), name="v1-operator-package-ziyarah"),
    path("operator/me/packages/status/", operator_packages.ManageHuzPackageStatusView.as_view(), name="v1-operator-package-status"),
    path("operator/me/hotels/", operator_packages.GetAllHotelsWithImagesView.as_view(), name="v1-operator-hotels"),

    path("admin/operators/profile/", partner_profile.GetPartnerProfileView.as_view(), name="v1-admin-operator-profile"),
    path("admin/operators/address/", partner_profile.GetPartnerAddressView.as_view(), name="v1-admin-operator-address"),
    path("admin/operators/wallet/banks/", partner_accounts_and_transactions.ManagePartnerBankAccountView.as_view(), name="v1-admin-operator-wallet-banks"),
    path("admin/operators/wallet/withdrawals/", partner_accounts_and_transactions.ManagePartnerWithdrawView.as_view(), name="v1-admin-operator-wallet-withdrawals"),
    path("admin/operators/wallet/transactions/", partner_accounts_and_transactions.GetPartnerAllTransactionHistoryView.as_view(), name="v1-admin-operator-wallet-transactions"),
    path("admin/operators/wallet/summary/", partner_accounts_and_transactions.GetPartnerTransactionOverallSummaryView.as_view(), name="v1-admin-operator-wallet-summary"),
    path("admin/operators/packages/", operator_packages.GetHuzShortPackageByTokenView.as_view(), name="v1-admin-operator-packages"),
    path("admin/operators/packages/detail/", operator_packages.GetHuzPackageDetailByTokenView.as_view(), name="v1-admin-operator-package-detail"),
    path("admin/operators/packages/statistics/", operator_packages.GetPartnersOverallPackagesStatisticsView.as_view(), name="v1-admin-operator-package-statistics"),
    path("admin/operators/bookings/", manage_partner_booking.GetBookingShortDetailForPartnersView.as_view(), name="v1-admin-operator-bookings"),
    path("admin/operators/bookings/detail/", manage_partner_booking.GetBookingDetailByBookingNumberForPartnerView.as_view(), name="v1-admin-operator-booking-detail"),
    path("admin/operators/bookings/action/", manage_partner_booking.TakeActionView.as_view(), name="v1-admin-operator-booking-action"),
    path("admin/operators/bookings/close/", manage_partner_booking.CloseBookingView.as_view(), name="v1-admin-operator-booking-close"),
    path("admin/operators/bookings/documents/", manage_partner_booking.ManageBookingDocumentsView.as_view(), name="v1-admin-operator-booking-documents"),
    path("admin/operators/bookings/document-delete/", manage_partner_booking.DeleteBookingDocumentsView.as_view(), name="v1-admin-operator-booking-document-delete"),
    path("admin/operators/bookings/airline-details/", manage_partner_booking.BookingAirlineDetailsView.as_view(), name="v1-admin-operator-booking-airline"),
    path("admin/operators/bookings/arrangements/", manage_partner_booking.BookingHotelAndTransportDetailsView.as_view(), name="v1-admin-operator-booking-arrangements"),
    path("admin/operators/bookings/issues/", manage_partner_booking.ReportBookingView.as_view(), name="v1-admin-operator-booking-issues"),
    path("admin/operators/bookings/ratings/summary/", manage_partner_booking.GetOverallRatingView.as_view(), name="v1-admin-operator-rating-summary"),
    path("admin/operators/bookings/ratings/package/", manage_partner_booking.GetRatingPackageWiseView.as_view(), name="v1-admin-operator-rating-package"),
    path("admin/operators/bookings/ratings/package-summary/", manage_partner_booking.GetPackageOverallRatingView.as_view(), name="v1-admin-operator-rating-package-summary"),
    path("admin/operators/bookings/complaints/", manage_partner_booking.GetPartnerComplaintsView.as_view(), name="v1-admin-operator-complaints"),
    path("admin/operators/bookings/complaints/detail/", manage_partner_booking.GetPartnerComplaintDetailView.as_view(), name="v1-admin-operator-complaints-detail"),
    path("admin/operators/bookings/complaints/summary/", manage_partner_booking.GetOverallPartnerComplaintsView.as_view(), name="v1-admin-operator-complaints-summary"),
    path("admin/operators/bookings/complaints/respond/", manage_partner_booking.GiveUpdateOnComplaintsView.as_view(), name="v1-admin-operator-complaints-respond"),
    path("admin/operators/bookings/statistics/", manage_partner_booking.GetPartnersOverallBookingStatisticsView.as_view(), name="v1-admin-operator-booking-statistics"),
    path("admin/operators/bookings/earnings/yearly/", manage_partner_booking.GetYearlyBookingStatisticsView.as_view(), name="v1-admin-operator-booking-earnings"),
    path("admin/operators/bookings/payments/", manage_partner_booking.PartnersBookingPaymentView.as_view(), name="v1-admin-operator-booking-payments"),
    path("admin/operators/dashboard/summary/", manage_partner_booking.GetOperatorDashboardSummaryView.as_view(), name="v1-admin-operator-dashboard-summary"),
]
