"""
Django settings for huz project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
import sys
from decouple import config, Csv
from corsheaders.defaults import default_headers

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def csv_config(name, default=""):
    values = config(name, cast=Csv(), default=default)
    return [str(value).strip() for value in values if str(value).strip()]


LOCAL_ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    ".ngrok-free.app",
    ".ngrok.io",
]

LOCAL_BROWSER_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:3001",
    "http://127.0.0.1:3001",
    "http://localhost:3002",
    "http://127.0.0.1:3002",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

LOCAL_BROWSER_ORIGIN_REGEXES = [
    r"^https://[a-z0-9-]+\.ngrok-free\.app$",
    r"^https://[a-z0-9-]+\.ngrok\.io$",
]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')
SECRET_KEY_FALLBACKS = [
    key
    for key in (
        config('SECRET_KEY1', default='').strip(),
        config('SECRET_KEY2', default='').strip(),
    )
    if key
]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
# DEBUG = True
ENABLE_API_DOCS = config('ENABLE_API_DOCS', cast=bool, default=False)
ENABLE_PERF_METRICS = config('ENABLE_PERF_METRICS', cast=bool, default=False)
PERF_METRICS_REQUEST_HEADER = config('PERF_METRICS_REQUEST_HEADER', default='X-Perf-Metrics').strip() or 'X-Perf-Metrics'
ENABLE_OPERATOR_DASHBOARD_SUMMARY_ENDPOINT = config(
    'ENABLE_OPERATOR_DASHBOARD_SUMMARY_ENDPOINT',
    cast=bool,
    default=True,
)
IS_RUNSERVER = len(sys.argv) > 1 and sys.argv[1].startswith("runserver")
APP_ENV = config("APP_ENV", default="development").strip().lower()
IS_PRODUCTION = APP_ENV == "production"
ALLOW_LOCALHOST_ORIGINS = config(
    "ALLOW_LOCALHOST_ORIGINS",
    cast=bool,
    default=not IS_PRODUCTION,
)

# These origin env vars are the reviewed deployment contract for the deployed
# web, operator, and admin browser clients. They make the intended production
# topology visible even when Django still uses the explicit host/CORS/CSRF
# lists below.
API_PUBLIC_ORIGIN = config("API_PUBLIC_ORIGIN", default="").strip().rstrip("/")
WEB_APP_ORIGIN = config("WEB_APP_ORIGIN", default="").strip().rstrip("/")
OPERATOR_APP_ORIGIN = config("OPERATOR_APP_ORIGIN", default="").strip().rstrip("/")
ADMIN_APP_ORIGIN = config("ADMIN_APP_ORIGIN", default="").strip().rstrip("/")

SERVE_MEDIA_AND_STATIC_FROM_DJANGO = config(
    'SERVE_MEDIA_AND_STATIC_FROM_DJANGO',
    cast=bool,
    default=IS_RUNSERVER,
)

ALLOWED_HOSTS = csv_config(
    'ALLOWED_HOSTS',
    default=",".join(LOCAL_ALLOWED_HOSTS),
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_yasg',
    'corsheaders',
    'common',
    'partners',
    'management',
    'booking',
]

REST_FRAMEWORK = {
    'DEFAULT_PARSER_CLASSES': (
       'rest_framework.parsers.JSONParser',
       'rest_framework.parsers.FormParser',
       'rest_framework.parsers.MultiPartParser',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'common.authentication.SessionTokenHeaderAuthentication',
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAdminUser',
        'rest_framework.permissions.IsAuthenticated',
        'rest_framework.permissions.AllowAny',
    ),
    'PAGINATE_BY': 10,
}

# Keep pagination opt-in on legacy APIViews until plain-list ListAPIView
# endpoints (for example chat inbox/message endpoints) are migrated.
DEFAULT_API_PAGE_SIZE = 10

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'common.middleware.RequestPerformanceMetricsMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = config('CORS_ALLOW_ALL_ORIGINS', cast=bool, default=False)
CORS_ALLOW_CREDENTIALS = config('CORS_ALLOW_CREDENTIALS', cast=bool, default=False)
CORS_ALLOWED_ORIGINS = csv_config(
    'CORS_ALLOWED_ORIGINS',
    default=",".join(LOCAL_BROWSER_ORIGINS if ALLOW_LOCALHOST_ORIGINS else []),
)
CORS_ALLOWED_ORIGIN_REGEXES = csv_config(
    'CORS_ALLOWED_ORIGIN_REGEXES',
    default=",".join(LOCAL_BROWSER_ORIGIN_REGEXES if ALLOW_LOCALHOST_ORIGINS else []),
)
CSRF_TRUSTED_ORIGINS = csv_config(
    'CSRF_TRUSTED_ORIGINS',
    default=",".join(LOCAL_BROWSER_ORIGINS if ALLOW_LOCALHOST_ORIGINS else []),
)
extra_cors_allow_headers = csv_config("CORS_ALLOW_HEADERS", default="")
CORS_ALLOW_HEADERS = list(
    dict.fromkeys(
        [
            *(str(header).strip().lower() for header in default_headers),
            *(str(header).strip().lower() for header in extra_cors_allow_headers if str(header).strip()),
            "x-partner-session",
        ]
    )
)

# CHANNEL_LAYERS = {
#     "default": {
#         "BACKEND": "channels.layers.InMemoryChannelLayer",
#     }
# }

ROOT_URLCONF = 'huz.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'huz/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'huz.wsgi.application'
# ASGI_APPLICATION = 'huz.asgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

database_options = {
    'connect_timeout': config('DB_CONNECT_TIMEOUT_SECONDS', cast=int, default=10),
}
db_ssl_ca = config('DB_SSL_CA', default='').strip()
if db_ssl_ca:
    database_options['ssl'] = {'ca': db_ssl_ca}

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),
        # Keep DB connections open across requests to avoid expensive reconnects
        # when using a remote MySQL host during local/dev runs.
        'CONN_MAX_AGE': config('DB_CONN_MAX_AGE', cast=int, default=300),
        'CONN_HEALTH_CHECKS': config('DB_CONN_HEALTH_CHECKS', cast=bool, default=True),
        'OPTIONS': database_options,
    }
}
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = config('USE_X_FORWARDED_HOST', cast=bool, default=True)
SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', cast=bool, default=False)
SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', cast=bool, default=False)
CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', cast=bool, default=False)
SESSION_COOKIE_SAMESITE = config('SESSION_COOKIE_SAMESITE', default='Lax')
CSRF_COOKIE_SAMESITE = config('CSRF_COOKIE_SAMESITE', default='Lax')
SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', cast=int, default=0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = config('SECURE_HSTS_INCLUDE_SUBDOMAINS', cast=bool, default=False)
SECURE_HSTS_PRELOAD = config('SECURE_HSTS_PRELOAD', cast=bool, default=False)
SECURE_CONTENT_TYPE_NOSNIFF = config('SECURE_CONTENT_TYPE_NOSNIFF', cast=bool, default=True)
SECURE_REFERRER_POLICY = config('SECURE_REFERRER_POLICY', default='same-origin')


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-file

STATIC_URL = '/static/'
MEDIA_URL = '/media/'


STATIC_ROOT = config(
    'STATIC_ROOT',
    default=str(BASE_DIR / ('static' if SERVE_MEDIA_AND_STATIC_FROM_DJANGO else 'staticfiles')),
)

MEDIA_ROOT = config('MEDIA_ROOT', default=str(BASE_DIR / 'media'))
FIREBASE_CREDENTIAL_PATH = config(
    'FIREBASE_CREDENTIAL_PATH',
    default='',
)
VIEW_LOG_PATH = config(
    'VIEW_LOG_PATH',
    default=str(BASE_DIR / 'view_logs.txt'),
)


EMAIL_ADDRESS = config('EMAIL_ADDRESS', default='HajjUmrah.co <no-reply@hajjumrah.co>')
EMAIL_ENVELOPE_SENDER = config('EMAIL_ENVELOPE_SENDER', default='').strip()
EMAIL_HOST = config('EMAIL_HOST', default='smtp.hostinger.com')
EMAIL_PORT = config('EMAIL_PORT', cast=int, default=465)
SERVER_EMAIL = config('SERVER_EMAIL', default='no-reply@hajjumrah.co')
SERVER_EMAIL_PASSWORD = config('SERVER_EMAIL_PASSWORD', default='')
EMAIL_DELIVERY_BACKEND = config('EMAIL_DELIVERY_BACKEND', default='smtp').strip().lower()
EMAIL_USE_SSL = config('EMAIL_USE_SSL', cast=bool, default=EMAIL_PORT == 465)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', cast=bool, default=(EMAIL_PORT == 587 and not EMAIL_USE_SSL))
EMAIL_STARTTLS_PORT = config('EMAIL_STARTTLS_PORT', cast=int, default=587)
EMAIL_ALLOW_STARTTLS_FALLBACK = config('EMAIL_ALLOW_STARTTLS_FALLBACK', cast=bool, default=True)
EMAIL_LOCAL_HOSTNAME = config('EMAIL_LOCAL_HOSTNAME', default='').strip()
EMAIL_SEND_TIMEOUT_SECONDS = config('EMAIL_SEND_TIMEOUT_SECONDS', cast=int, default=20)
EMAIL_TRANSIENT_SMTP_RETRIES = config('EMAIL_TRANSIENT_SMTP_RETRIES', cast=int, default=2)
EMAIL_TRANSIENT_SMTP_RETRY_DELAY_SECONDS = config('EMAIL_TRANSIENT_SMTP_RETRY_DELAY_SECONDS', cast=int, default=2)
EMAIL_OTP_EXPIRY_MINUTES = config('EMAIL_OTP_EXPIRY_MINUTES', cast=int, default=5)
PASSWORD_RESET_EXPIRY_MINUTES = config('PASSWORD_RESET_EXPIRY_MINUTES', cast=int, default=60)
OPERATOR_PANEL_BASE_URL = config(
    'OPERATOR_PANEL_BASE_URL',
    default=(OPERATOR_APP_ORIGIN or 'http://localhost:3000'),
).strip().rstrip("/")

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
